Resources:
  MiServidor:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-053a45fff0a704a47
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref GrupoDeSeguridad

  # Grupo de seguridad Web
  GrupoDeSeguridad:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Habilita el acceso SSH
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
